### ISSUE TITLE
Apple will not approve LC.app updates

### ISSUE THREAD

**Issue by patch-e** [latestchatty/latest-chatty-ios#148]
I ran into a bit of an issue with the most recent update I submitted to the App Store for approval. The new version doesn't add any new features really, just cleaning up some code and migrating Fabric/Crashlytics analytics to Firebase (which is a requirement later this year from Google as they merge & shutdown Fabric into Firebase).

Anyways, Apple denied the app update for breaking Guideline 1.2. I don't think this guideline is new, but maybe they are enforcing it more. I am concerned about the fact that they call out implementing "all" of the bullet points. Filtering objectionable content is already possible within settings, but none of the other bullet points are implemented in the app. The last one about acting on objectionable content within 24 hours isn't even possible really.

Thoughts on this? What should I do?

---

**Guideline 1.2 - Safety - User Generated Content**

Your app enables the display of user-generated content but does not have the proper precautions in place.

Next Steps
To resolve this issue, please revise your app to implement **all** of the following precautions:

- Require that users agree to terms (EULA) and these terms must make it clear that there is no tolerance for objectionable content or abusive users
- A method for filtering objectionable content
- A mechanism for users to flag objectionable content
- A mechanism for users to block abusive users
- The developer must act on objectionable content reports within 24 hours by removing the content and ejecting the user who provided the offending content

**Comment by tomkidd** [comment]
Either

a) write to them and ask for more info, explain that this has never been a problem before, etc. I’ve got a client that’s run into this before and after some brief discussion with them they went ahead and accepted it 

or

b) rebuild and resubmit, maybe you’ll get a different reviewer the next time around. This is probably a newer reviewer who doesn’t know what they’re doing yet.

**Comment by patch-e** [comment]
I think I will try writing them back. I totally forgot that LC.app has the mod tools built in (no idea if they still work!) so I can try to use that as leverage. I wonder if it would help to link the shack guidelines in my reply (https://www.shacknews.com/guidelines). I could pretty easily slap a button in the app that links to the guidelines too.

**Comment by electroly** [comment]
Knowing nothing about this, my thought is to lie about anything we can't really control. Like if the Shack guidelines aren't good enough to qualify as the EULA, just put in a click-through EULA for LC.app that never actually gets enforced by anyone. If we need a report button in order to save LC.app, we can wire it up to an SM to duke nuked.

**Comment by Squeegy** [comment]
How about popping up the guidelines page in a webview on first launch, and then never ever again.

**Comment by patch-e** [comment]
Submitted a new version with a few minor changes and information back to Apple about moderators, etc. These were the programmatic changes in the update:
- Off-topic, politics / religion, and stupid filter categories now defaulted to OFF for fresh app install with no existing iCloud settings being ported over
- Added link to Shack Guidelines in "About" section of Settings view

It wasn't enough. They rejected it again calling out "Does your app contain a reporting, blocking mechanism and EULA? If yes, where can we find these mechanisms?". I guess I will add the one-time click-through EULA pointing to the Shack guidelines and a simple report action that pops up a SM compose view aimed at Duke Nuked like electroly suggested. I am going to ignore their "blocking mechanism" comment at this time. 

On a related side-note, the terms & conditions linked to from the Shack's own account registration process doesn't even work. The anchor in the registration modal goes no where and when I did find the terms & conditions URL manually, it's CSS is broke as hell: [https://www.shacknews.com/tou](https://www.shacknews.com/tou). The [privacy policy](https://www.shacknews.com/privacy) is the same way broken CSS-wise, but is at least linked to correctly, lol.

**Comment by patch-e** [comment]
That update was a pain in the butt, but finally accepted by Apple. Not sure why they are cracking down on the app so much nowadays. I had to put in a cheesy report feature like @electroly suggested, tweak default filters, prompt guidelines on first launch similar to what @Squeegy suggested, and basically bluffed that the existing collapse thread feature was a sufficient "blocking" mechanism but they accepted the answer.
